version: '3'
services:
    pendurai-api:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env/pendurai_api.env
        volumes:
            - ./src:/app/src
        ports:
            - "3000:3000"
        command: npm start
    pendurai-mariadb:
        image: mariadb:latest
        env_file:
            - .env/mariadb.env
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
